package graduation.mcs.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "attendance".
 */
public class Attendance {

    private Long id;
    /** Not-null value. */
    private String conference_uuid;
    /** Not-null value. */
    private String account_phone;
    /** Not-null value. */
    private String account_nickname;
    private Long time_sign;
    private String place_sign;

    public Attendance() {
    }

    public Attendance(Long id) {
        this.id = id;
    }

    public Attendance(Long id, String conference_uuid, String account_phone, String account_nickname, Long time_sign, String place_sign) {
        this.id = id;
        this.conference_uuid = conference_uuid;
        this.account_phone = account_phone;
        this.account_nickname = account_nickname;
        this.time_sign = time_sign;
        this.place_sign = place_sign;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getConference_uuid() {
        return conference_uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setConference_uuid(String conference_uuid) {
        this.conference_uuid = conference_uuid;
    }

    /** Not-null value. */
    public String getAccount_phone() {
        return account_phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount_phone(String account_phone) {
        this.account_phone = account_phone;
    }

    /** Not-null value. */
    public String getAccount_nickname() {
        return account_nickname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccount_nickname(String account_nickname) {
        this.account_nickname = account_nickname;
    }

    public Long getTime_sign() {
        return time_sign;
    }

    public void setTime_sign(Long time_sign) {
        this.time_sign = time_sign;
    }

    public String getPlace_sign() {
        return place_sign;
    }

    public void setPlace_sign(String place_sign) {
        this.place_sign = place_sign;
    }

}
