package graduation.mcs.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import graduation.mcs.dao.ConferenceSigned;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "conference_signed".
*/
public class ConferenceSignedDao extends AbstractDao<ConferenceSigned, Long> {

    public static final String TABLENAME = "conference_signed";

    /**
     * Properties of entity ConferenceSigned.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Conference_uuid = new Property(1, String.class, "conference_uuid", false, "CONFERENCE_UUID");
        public final static Property Creator_account_phone = new Property(2, String.class, "creator_account_phone", false, "CREATOR_ACCOUNT_PHONE");
        public final static Property Sign_account_phone = new Property(3, String.class, "sign_account_phone", false, "SIGN_ACCOUNT_PHONE");
        public final static Property Time_create = new Property(4, long.class, "time_create", false, "TIME_CREATE");
        public final static Property Time_begin = new Property(5, long.class, "time_begin", false, "TIME_BEGIN");
        public final static Property Time_end = new Property(6, long.class, "time_end", false, "TIME_END");
        public final static Property Theme = new Property(7, String.class, "theme", false, "THEME");
        public final static Property Description = new Property(8, String.class, "description", false, "DESCRIPTION");
        public final static Property Place = new Property(9, String.class, "place", false, "PLACE");
        public final static Property Icon_img = new Property(10, byte[].class, "icon_img", false, "ICON_IMG");
    };


    public ConferenceSignedDao(DaoConfig config) {
        super(config);
    }
    
    public ConferenceSignedDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"conference_signed\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CONFERENCE_UUID\" TEXT NOT NULL ," + // 1: conference_uuid
                "\"CREATOR_ACCOUNT_PHONE\" TEXT NOT NULL ," + // 2: creator_account_phone
                "\"SIGN_ACCOUNT_PHONE\" TEXT NOT NULL ," + // 3: sign_account_phone
                "\"TIME_CREATE\" INTEGER NOT NULL ," + // 4: time_create
                "\"TIME_BEGIN\" INTEGER NOT NULL ," + // 5: time_begin
                "\"TIME_END\" INTEGER NOT NULL ," + // 6: time_end
                "\"THEME\" TEXT NOT NULL ," + // 7: theme
                "\"DESCRIPTION\" TEXT," + // 8: description
                "\"PLACE\" TEXT NOT NULL ," + // 9: place
                "\"ICON_IMG\" BLOB);"); // 10: icon_img
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"conference_signed\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ConferenceSigned entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getConference_uuid());
        stmt.bindString(3, entity.getCreator_account_phone());
        stmt.bindString(4, entity.getSign_account_phone());
        stmt.bindLong(5, entity.getTime_create());
        stmt.bindLong(6, entity.getTime_begin());
        stmt.bindLong(7, entity.getTime_end());
        stmt.bindString(8, entity.getTheme());
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
        stmt.bindString(10, entity.getPlace());
 
        byte[] icon_img = entity.getIcon_img();
        if (icon_img != null) {
            stmt.bindBlob(11, icon_img);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ConferenceSigned readEntity(Cursor cursor, int offset) {
        ConferenceSigned entity = new ConferenceSigned( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // conference_uuid
            cursor.getString(offset + 2), // creator_account_phone
            cursor.getString(offset + 3), // sign_account_phone
            cursor.getLong(offset + 4), // time_create
            cursor.getLong(offset + 5), // time_begin
            cursor.getLong(offset + 6), // time_end
            cursor.getString(offset + 7), // theme
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // description
            cursor.getString(offset + 9), // place
            cursor.isNull(offset + 10) ? null : cursor.getBlob(offset + 10) // icon_img
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ConferenceSigned entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setConference_uuid(cursor.getString(offset + 1));
        entity.setCreator_account_phone(cursor.getString(offset + 2));
        entity.setSign_account_phone(cursor.getString(offset + 3));
        entity.setTime_create(cursor.getLong(offset + 4));
        entity.setTime_begin(cursor.getLong(offset + 5));
        entity.setTime_end(cursor.getLong(offset + 6));
        entity.setTheme(cursor.getString(offset + 7));
        entity.setDescription(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPlace(cursor.getString(offset + 9));
        entity.setIcon_img(cursor.isNull(offset + 10) ? null : cursor.getBlob(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ConferenceSigned entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ConferenceSigned entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
