package graduation.mcs.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import graduation.mcs.dao.Account;
import graduation.mcs.dao.Conference;
import graduation.mcs.dao.Man;
import graduation.mcs.dao.Attendance;
import graduation.mcs.dao.ConferenceSigned;

import graduation.mcs.dao.AccountDao;
import graduation.mcs.dao.ConferenceDao;
import graduation.mcs.dao.ManDao;
import graduation.mcs.dao.AttendanceDao;
import graduation.mcs.dao.ConferenceSignedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig conferenceDaoConfig;
    private final DaoConfig manDaoConfig;
    private final DaoConfig attendanceDaoConfig;
    private final DaoConfig conferenceSignedDaoConfig;

    private final AccountDao accountDao;
    private final ConferenceDao conferenceDao;
    private final ManDao manDao;
    private final AttendanceDao attendanceDao;
    private final ConferenceSignedDao conferenceSignedDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        conferenceDaoConfig = daoConfigMap.get(ConferenceDao.class).clone();
        conferenceDaoConfig.initIdentityScope(type);

        manDaoConfig = daoConfigMap.get(ManDao.class).clone();
        manDaoConfig.initIdentityScope(type);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        conferenceSignedDaoConfig = daoConfigMap.get(ConferenceSignedDao.class).clone();
        conferenceSignedDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        conferenceDao = new ConferenceDao(conferenceDaoConfig, this);
        manDao = new ManDao(manDaoConfig, this);
        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);
        conferenceSignedDao = new ConferenceSignedDao(conferenceSignedDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Conference.class, conferenceDao);
        registerDao(Man.class, manDao);
        registerDao(Attendance.class, attendanceDao);
        registerDao(ConferenceSigned.class, conferenceSignedDao);
    }
    
    public void clear() {
        accountDaoConfig.getIdentityScope().clear();
        conferenceDaoConfig.getIdentityScope().clear();
        manDaoConfig.getIdentityScope().clear();
        attendanceDaoConfig.getIdentityScope().clear();
        conferenceSignedDaoConfig.getIdentityScope().clear();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public ConferenceDao getConferenceDao() {
        return conferenceDao;
    }

    public ManDao getManDao() {
        return manDao;
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

    public ConferenceSignedDao getConferenceSignedDao() {
        return conferenceSignedDao;
    }

}
