package graduation.mcs.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import graduation.mcs.dao.Man;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "conference_special_men".
*/
public class ManDao extends AbstractDao<Man, Long> {

    public static final String TABLENAME = "conference_special_men";

    /**
     * Properties of entity Man.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Account_phone = new Property(1, String.class, "account_phone", false, "ACCOUNT_PHONE");
        public final static Property Conference_uuid = new Property(2, String.class, "conference_uuid", false, "CONFERENCE_UUID");
        public final static Property Conference_id = new Property(3, long.class, "conference_id", false, "CONFERENCE_ID");
    };

    private DaoSession daoSession;

    private Query<Man> conference_MenQuery;

    public ManDao(DaoConfig config) {
        super(config);
    }
    
    public ManDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"conference_special_men\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACCOUNT_PHONE\" TEXT," + // 1: account_phone
                "\"CONFERENCE_UUID\" TEXT," + // 2: conference_uuid
                "\"CONFERENCE_ID\" INTEGER NOT NULL );"); // 3: conference_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"conference_special_men\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Man entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String account_phone = entity.getAccount_phone();
        if (account_phone != null) {
            stmt.bindString(2, account_phone);
        }
 
        String conference_uuid = entity.getConference_uuid();
        if (conference_uuid != null) {
            stmt.bindString(3, conference_uuid);
        }
        stmt.bindLong(4, entity.getConference_id());
    }

    @Override
    protected void attachEntity(Man entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Man readEntity(Cursor cursor, int offset) {
        Man entity = new Man( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // account_phone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // conference_uuid
            cursor.getLong(offset + 3) // conference_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Man entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccount_phone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setConference_uuid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setConference_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Man entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Man entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "men" to-many relationship of Conference. */
    public List<Man> _queryConference_Men(long conference_id) {
        synchronized (this) {
            if (conference_MenQuery == null) {
                QueryBuilder<Man> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Conference_id.eq(null));
                queryBuilder.orderRaw("T.'ACCOUNT_PHONE' ASC");
                conference_MenQuery = queryBuilder.build();
            }
        }
        Query<Man> query = conference_MenQuery.forCurrentThread();
        query.setParameter(0, conference_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getConferenceDao().getAllColumns());
            builder.append(" FROM conference_special_men T");
            builder.append(" LEFT JOIN conference T0 ON T.\"CONFERENCE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Man loadCurrentDeep(Cursor cursor, boolean lock) {
        Man entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Conference conference = loadCurrentOther(daoSession.getConferenceDao(), cursor, offset);
         if(conference != null) {
            entity.setConference(conference);
        }

        return entity;    
    }

    public Man loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Man> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Man> list = new ArrayList<Man>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Man> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Man> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
